#! /usr/bin/env Rscript
## This runs testme test script inst/testme/test-BatchtoolsFutureBackend.R
## Don't edit - it was autogenerated by inst/testme/deploy.R
future.batchtools:::testme("BatchtoolsFutureBackend")
